Repository open-mmlab/mmdetection3d, pull requests merged in 2022-10, with the labels that each got.

#1845 [Refactor] Update custom datasets doc
  docs/en/advanced_guides/customize_dataset.md
Labels: v-1.x

#1833 [Refactor]fix sunrgb lyft doc
  docs/en/advanced_guides/datasets/lyft_det.md
  docs/en/advanced_guides/datasets/scannet_det.md
  docs/en/advanced_guides/datasets/sunrgbd_det.md
Labels: v-1.x

#1882 [Fix]: Fix nuscenes dataset training
  mmdet3d/datasets/det3d_dataset.py
  mmdet3d/datasets/kitti_dataset.py
  mmdet3d/datasets/lyft_dataset.py
  mmdet3d/datasets/nuscenes_dataset.py
  mmdet3d/datasets/scannet_dataset.py
  mmdet3d/datasets/sunrgbd_dataset.py
  mmdet3d/datasets/waymo_dataset.py
  tools/dataset_converters/update_infos_to_v2.py
Labels: need-fix-lint

#1816 [Fix] fix some mono3d related bugs
  configs/_base_/datasets/kitti-mono3d.py
  configs/_base_/datasets/nus-mono3d.py
  configs/pgd/pgd_r101-caffe_fpn_head-gn_4xb3-4x_kitti-mono3d.py
  configs/smoke/smoke_dla34_dlaneck_gn-all_4xb8-6x_kitti-mono3d.py
  demo/mono_det_demo.py
  demo/multi_modality_demo.py
  demo/pcd_demo.py
  demo/pcd_seg_demo.py
  docs/zh_cn/user_guides/useful_tools.md
  mmdet3d/datasets/__init__.py
  mmdet3d/datasets/convert_utils.py
  mmdet3d/datasets/kitti_dataset.py
  mmdet3d/datasets/nuscenes_dataset.py
  mmdet3d/datasets/transforms/__init__.py
  mmdet3d/datasets/transforms/transforms_3d.py
  mmdet3d/datasets/waymo_dataset.py
  mmdet3d/evaluation/metrics/waymo_metric.py
  mmdet3d/visualization/local_visualizer.py
  tools/dataset_converters/update_infos_to_v2.py
  tools/misc/browse_dataset.py
Labels: v-1.x

#1857 [Refactor] update `Det3DLocalVisualization` and visualization documentation
  configs/_base_/datasets/kitti-3d-3class.py
  configs/_base_/datasets/kitti-3d-car.py
  configs/_base_/datasets/kitti-mono3d.py
  configs/_base_/datasets/lyft-3d.py
  configs/_base_/datasets/nus-3d.py
  configs/_base_/datasets/nus-mono3d.py
  configs/_base_/datasets/s3dis-seg.py
  configs/_base_/datasets/scannet-3d.py
  configs/_base_/datasets/scannet-seg.py
  configs/_base_/datasets/sunrgbd-3d.py
  configs/_base_/datasets/waymoD5-3d-3class.py
  configs/_base_/datasets/waymoD5-3d-car.py
  configs/_base_/default_runtime.py
  docs/en/user_guides/index.rst
  docs/en/user_guides/visualization.md
  mmdet3d/engine/hooks/visualization_hook.py
  mmdet3d/visualization/local_visualizer.py
Labels: v-1.x

#1716 [Features] Support waymo challenge solution
  .gitignore
  configs/_base_/datasets/waymoD5-mono3d-3class.py
  configs/_base_/datasets/waymoD5-mv3d-3class.py
  configs/_base_/models/multiview_dfm.py
  configs/dfm/multiview-dfm_r101-dcn_16xb2_waymoD5-3d-3class.py
  configs/dfm/multiview-dfm_r101-dcn_centerhead_16xb2_waymoD5-3d-3class.py
  mmdet3d/datasets/transforms/__init__.py
  mmdet3d/datasets/transforms/formating.py
  mmdet3d/datasets/transforms/loading.py
  mmdet3d/datasets/transforms/transforms_3d.py
  mmdet3d/datasets/waymo_dataset.py
  mmdet3d/evaluation/metrics/kitti_metric.py
  mmdet3d/evaluation/metrics/waymo_metric.py
  mmdet3d/models/data_preprocessors/data_preprocessor.py
  mmdet3d/models/data_preprocessors/utils.py
  mmdet3d/models/detectors/__init__.py
  mmdet3d/models/detectors/dfm.py
  mmdet3d/models/detectors/imvoxelnet.py
  mmdet3d/models/detectors/multiview_dfm.py
  mmdet3d/models/layers/fusion_layers/point_fusion.py
  mmdet3d/structures/bbox_3d/utils.py
  mmdet3d/utils/misc.py
Labels: v-1.x

#1956 [Fix] Fix `to` function of BaseInstance3DBoxes
  mmdet3d/structures/bbox_3d/base_box3d.py
Labels: P0

#1928 Fix PonitRCNN GPU memory occupancy problem
  docs/en/changelog.md
  mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py
  mmdet3d/models/roi_heads/point_rcnn_roi_head.py
  tests/test_models/test_heads/test_parta2_bbox_head.py
Labels: bug
